language: ruby

rvm:
  - 2.3.3

env:
  global:
    - APP_IMG: "devopsrecipes/rubydockerapp"
    - NIGHTLY_TRIGGER_JOB: "ruby_docker_nightly_timer"

integrations:
  hub:
    - integrationName: dr_dockerhub
      type: dockerRegistryLogin

build:
  ci:
    - bundle install --without production
    - rails db:migrate
    - rails test
    - |
        if ( [ $JOB_TRIGGERED_BY_NAME == $NIGHTLY_TRIGGER_JOB ] )
        then
          docker build -t devopsrecipes/rubydockerapp:nightly --build-arg FROM_IMG=phusion/baseimage:0.9.22 .
          docker push devopsrecipes/rubydockerapp:nightly
        else
          docker build -t devopsrecipes/rubydockerapp:latest --build-arg FROM_IMG=devopsrecipes/rubydockerapp:nightly .
          docker push devopsrecipes/rubydockerapp:latest
        fi

resources:
  - name: ruby_docker_nightly_timer
    type: time
    versionTemplate:
      interval: "0 2 * * *"   # Triggers at 2 am GMT

jobs:
  - name: ruby_docker_build_runCI
    type: runCI
    steps:
      - IN: ruby_docker_nightly_timer
      - TASK:
          script:
            - ls